//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Views.Haber {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Views.Haber.ListStrings", typeof(ListStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string ButtonBuscar {
            get {
                return ResourceManager.GetString("ButtonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string ButtonGuardar {
            get {
                return ResourceManager.GetString("ButtonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe Servicios Básicos.
        /// </summary>
        public static string ButtonInformeServicios {
            get {
                return ResourceManager.GetString("ButtonInformeServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string ButtonLimpiar {
            get {
                return ResourceManager.GetString("ButtonLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string ButtonNuevo {
            get {
                return ResourceManager.GetString("ButtonNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa:.
        /// </summary>
        public static string LabelEmpresa {
            get {
                return ResourceManager.GetString("LabelEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string LabelFecha {
            get {
                return ResourceManager.GetString("LabelFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desde:.
        /// </summary>
        public static string LabelFechaDesde {
            get {
                return ResourceManager.GetString("LabelFechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Hasta:.
        /// </summary>
        public static string LabelFechaHasta {
            get {
                return ResourceManager.GetString("LabelFechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto:.
        /// </summary>
        public static string LabelMonto {
            get {
                return ResourceManager.GetString("LabelMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        public static string LabelObservacion {
            get {
                return ResourceManager.GetString("LabelObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio Básico:.
        /// </summary>
        public static string LabelServicioBasico {
            get {
                return ResourceManager.GetString("LabelServicioBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de haber:.
        /// </summary>
        public static string LabelTipoHaber {
            get {
                return ResourceManager.GetString("LabelTipoHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moneda:.
        /// </summary>
        public static string LabelTipoMoneda {
            get {
                return ResourceManager.GetString("LabelTipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string TextFiltros {
            get {
                return ResourceManager.GetString("TextFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haberes.
        /// </summary>
        public static string TextSeccionResultado {
            get {
                return ResourceManager.GetString("TextSeccionResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportadora Haruhiko.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Haberes.
        /// </summary>
        public static string TittleListado {
            get {
                return ResourceManager.GetString("TittleListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Informe de Servicios Básicos.
        /// </summary>
        public static string TittlePopUpInforme {
            get {
                return ResourceManager.GetString("TittlePopUpInforme", resourceCulture);
            }
        }
    }
}
