//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonServiceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonServiceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Services.CommonServiceStrings", typeof(CommonServiceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado actual del pedido es &quot;{0}&quot; y ha pasado al estado &quot;{1}&quot;..
        /// </summary>
        public static string TextSegCambioEstado {
            get {
                return ResourceManager.GetString("TextSegCambioEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado actual del fichero es &quot;{0}&quot; y ha pasado al estado &quot;{1}&quot;..
        /// </summary>
        public static string TextSegCambioEstadoFichero {
            get {
                return ResourceManager.GetString("TextSegCambioEstadoFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha añadido correctamente el fichero {0}..
        /// </summary>
        public static string TextSegCrearFichero {
            get {
                return ResourceManager.GetString("TextSegCrearFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha añadido correctamente el fichero {0} y su estado es &quot;Recibido&quot;..
        /// </summary>
        public static string TextSegCrearFicheroEstado {
            get {
                return ResourceManager.GetString("TextSegCrearFicheroEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado correctamente el pedido y su estado es &quot;Inicio&quot;..
        /// </summary>
        public static string TextSegCrearPedido {
            get {
                return ResourceManager.GetString("TextSegCrearPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha eliminado correctamente el fichero {0}..
        /// </summary>
        public static string TextSegEliminarFichero {
            get {
                return ResourceManager.GetString("TextSegEliminarFichero", resourceCulture);
            }
        }
    }
}
