//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Scripts.Haberes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Scripts.Haberes.ListStrings", typeof(ListStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string ColumnAcciones {
            get {
                return ResourceManager.GetString("ColumnAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string ColumnFecha {
            get {
                return ResourceManager.GetString("ColumnFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string ColumnMonto {
            get {
                return ResourceManager.GetString("ColumnMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string ColumnObservacion {
            get {
                return ResourceManager.GetString("ColumnObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio Básico.
        /// </summary>
        public static string ColumnServicioBasico {
            get {
                return ResourceManager.GetString("ColumnServicioBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Haber.
        /// </summary>
        public static string ColumnTipoHaber {
            get {
                return ResourceManager.GetString("ColumnTipoHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoherencia en el rango de fechas..
        /// </summary>
        public static string ErrorFechaIncoherente {
            get {
                return ResourceManager.GetString("ErrorFechaIncoherente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha no puede ser mayor al día actual..
        /// </summary>
        public static string ErrorFechaMayor {
            get {
                return ResourceManager.GetString("ErrorFechaMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha introducida no puede ser mayor a la fecha actual..
        /// </summary>
        public static string ErrorFechaMayorHoy {
            get {
                return ResourceManager.GetString("ErrorFechaMayorHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una fecha..
        /// </summary>
        public static string ErrorNoFecha {
            get {
                return ResourceManager.GetString("ErrorNoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un monto..
        /// </summary>
        public static string ErrorNoMonto {
            get {
                return ResourceManager.GetString("ErrorNoMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una observación..
        /// </summary>
        public static string ErrorNoObservacion {
            get {
                return ResourceManager.GetString("ErrorNoObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un servicio básico..
        /// </summary>
        public static string ErrorNoServicioBasico {
            get {
                return ResourceManager.GetString("ErrorNoServicioBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de haber..
        /// </summary>
        public static string ErrorNoTipoHaber {
            get {
                return ResourceManager.GetString("ErrorNoTipoHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de moneda..
        /// </summary>
        public static string ErrorNoTipoMoneda {
            get {
                return ResourceManager.GetString("ErrorNoTipoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está a punto de eliminar el registro, ¿Desea continuar?.
        /// </summary>
        public static string TextConfirmarEliminar {
            get {
                return ResourceManager.GetString("TextConfirmarEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string TextEditar {
            get {
                return ResourceManager.GetString("TextEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string TextEliminar {
            get {
                return ResourceManager.GetString("TextEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Haberes.
        /// </summary>
        public static string TittlePopUp {
            get {
                return ResourceManager.GetString("TittlePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Haber.
        /// </summary>
        public static string TituloPopUp {
            get {
                return ResourceManager.GetString("TituloPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Haber.
        /// </summary>
        public static string TituloPopUpEditar {
            get {
                return ResourceManager.GetString("TituloPopUpEditar", resourceCulture);
            }
        }
    }
}
