//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Scripts.Pedidos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditarStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditarStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Scripts.Pedidos.EditarStrings", typeof(EditarStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string ColumnDescripcion {
            get {
                return ResourceManager.GetString("ColumnDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string ColumnFecha {
            get {
                return ResourceManager.GetString("ColumnFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        public static string ColumnOperador {
            get {
                return ResourceManager.GetString("ColumnOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string ColumnTipo {
            get {
                return ResourceManager.GetString("ColumnTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero ha excedido el tamaño permitido..
        /// </summary>
        public static string ErrorArchivoExcedioLongitud {
            get {
                return ResourceManager.GetString("ErrorArchivoExcedioLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero se encuentra vacío..
        /// </summary>
        public static string ErrorFicheroVacio {
            get {
                return ResourceManager.GetString("ErrorFicheroVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de eliminar el fichero?.
        /// </summary>
        public static string MessageConfirmDeleteFile {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string TextDownload {
            get {
                return ResourceManager.GetString("TextDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibido.
        /// </summary>
        public static string TextRecibido {
            get {
                return ResourceManager.GetString("TextRecibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir.
        /// </summary>
        public static string TextSubir {
            get {
                return ResourceManager.GetString("TextSubir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
    }
}
