//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Scripts.Pedidos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Scripts.Pedidos.ListStrings", typeof(ListStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string ColumnAcciones {
            get {
                return ResourceManager.GetString("ColumnAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnet.
        /// </summary>
        public static string ColumnCarnet {
            get {
                return ResourceManager.GetString("ColumnCarnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string ColumnCliente {
            get {
                return ResourceManager.GetString("ColumnCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenedor.
        /// </summary>
        public static string ColumnContenedor {
            get {
                return ResourceManager.GetString("ColumnContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string ColumnDescripcion {
            get {
                return ResourceManager.GetString("ColumnDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string ColumnEstado {
            get {
                return ResourceManager.GetString("ColumnEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string ColumnFecha {
            get {
                return ResourceManager.GetString("ColumnFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoherencia en el rango de fechas..
        /// </summary>
        public static string ErrorFechaIncoherente {
            get {
                return ResourceManager.GetString("ErrorFechaIncoherente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Cliente..
        /// </summary>
        public static string ErrorNoCliente {
            get {
                return ResourceManager.GetString("ErrorNoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca un valor en el campo Descripción..
        /// </summary>
        public static string ErrorNoDescripcion {
            get {
                return ResourceManager.GetString("ErrorNoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string TextEditar {
            get {
                return ResourceManager.GetString("TextEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string TextEliminar {
            get {
                return ResourceManager.GetString("TextEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string TextObservaciones {
            get {
                return ResourceManager.GetString("TextObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string TextPagos {
            get {
                return ResourceManager.GetString("TextPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de pedidos.
        /// </summary>
        public static string TituloPopUp {
            get {
                return ResourceManager.GetString("TituloPopUp", resourceCulture);
            }
        }
    }
}
