//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Views.Pedido {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Views.Pedido.CreateStrings", typeof(CreateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente*:.
        /// </summary>
        public static string LabelCliente {
            get {
                return ResourceManager.GetString("LabelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenedor:.
        /// </summary>
        public static string LabelContenedor {
            get {
                return ResourceManager.GetString("LabelContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción*:.
        /// </summary>
        public static string LabelDescripcion {
            get {
                return ResourceManager.GetString("LabelDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección:.
        /// </summary>
        public static string LabelDireccion {
            get {
                return ResourceManager.GetString("LabelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Dirección:.
        /// </summary>
        public static string LabelDireccionUrl {
            get {
                return ResourceManager.GetString("LabelDireccionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio:.
        /// </summary>
        public static string LabelPrecio {
            get {
                return ResourceManager.GetString("LabelPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Cobro.
        /// </summary>
        public static string TitleCobro {
            get {
                return ResourceManager.GetString("TitleCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo pedido.
        /// </summary>
        public static string TitleCrear {
            get {
                return ResourceManager.GetString("TitleCrear", resourceCulture);
            }
        }
    }
}
