//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Views.Pedido {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditarStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditarStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Views.Pedido.EditarStrings", typeof(EditarStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Recibí Conforme.
        /// </summary>
        public static string BtnRecibiConforme {
            get {
                return ResourceManager.GetString("BtnRecibiConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL:.
        /// </summary>
        public static string LabelBL {
            get {
                return ResourceManager.GetString("LabelBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente:.
        /// </summary>
        public static string LabelCliente {
            get {
                return ResourceManager.GetString("LabelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenedor:.
        /// </summary>
        public static string LabelContenedor {
            get {
                return ResourceManager.GetString("LabelContenedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRT:.
        /// </summary>
        public static string LabelCrt {
            get {
                return ResourceManager.GetString("LabelCrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dam:.
        /// </summary>
        public static string LabelDam {
            get {
                return ResourceManager.GetString("LabelDam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAV:.
        /// </summary>
        public static string LabelDav {
            get {
                return ResourceManager.GetString("LabelDav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección:.
        /// </summary>
        public static string LabelDireccion {
            get {
                return ResourceManager.GetString("LabelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Dirección:.
        /// </summary>
        public static string LabelDireccionUrl {
            get {
                return ResourceManager.GetString("LabelDireccionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUI:.
        /// </summary>
        public static string LabelDui {
            get {
                return ResourceManager.GetString("LabelDui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa:.
        /// </summary>
        public static string LabelEmpresa {
            get {
                return ResourceManager.GetString("LabelEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        public static string LabelEstado {
            get {
                return ResourceManager.GetString("LabelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura Comercial:.
        /// </summary>
        public static string LabelFacturaComercial {
            get {
                return ResourceManager.GetString("LabelFacturaComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOC:.
        /// </summary>
        public static string LabelGoc {
            get {
                return ResourceManager.GetString("LabelGoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes:.
        /// </summary>
        public static string LabelImagenes {
            get {
                return ResourceManager.GetString("LabelImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Empaque:.
        /// </summary>
        public static string LabelListaEmpaque {
            get {
                return ResourceManager.GetString("LabelListaEmpaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIC:.
        /// </summary>
        public static string LabelMic {
            get {
                return ResourceManager.GetString("LabelMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte Recepción:.
        /// </summary>
        public static string LabelParteRecepcion {
            get {
                return ResourceManager.GetString("LabelParteRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibí Conforme:.
        /// </summary>
        public static string LabelRecibiConforme {
            get {
                return ResourceManager.GetString("LabelRecibiConforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicoin:.
        /// </summary>
        public static string LabelSicoin {
            get {
                return ResourceManager.GetString("LabelSicoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        public static string LabelTelefono {
            get {
                return ResourceManager.GetString("LabelTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string SectionInformacion {
            get {
                return ResourceManager.GetString("SectionInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencia Despachante.
        /// </summary>
        public static string TabAgenciaDespachante {
            get {
                return ResourceManager.GetString("TabAgenciaDespachante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desaduanización.
        /// </summary>
        public static string TabDesaduanizacion {
            get {
                return ResourceManager.GetString("TabDesaduanizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega.
        /// </summary>
        public static string TabEntrega {
            get {
                return ResourceManager.GetString("TabEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importadora.
        /// </summary>
        public static string TabImportadora {
            get {
                return ResourceManager.GetString("TabImportadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimientos.
        /// </summary>
        public static string TabSeguimientos {
            get {
                return ResourceManager.GetString("TabSeguimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora.
        /// </summary>
        public static string TabTransportadora {
            get {
                return ResourceManager.GetString("TabTransportadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pedido.
        /// </summary>
        public static string TittleListado {
            get {
                return ResourceManager.GetString("TittleListado", resourceCulture);
            }
        }
    }
}
