//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransHaruhiko.Globalization.Views.Poliza {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransHaruhiko.Globalization.Views.Poliza.ListStrings", typeof(ListStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string ButtonAnhadir {
            get {
                return ResourceManager.GetString("ButtonAnhadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ButtonNuevo {
            get {
                return ResourceManager.GetString("ButtonNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Planilla de Despacho.
        /// </summary>
        public static string ButtonPlanillaDespacho {
            get {
                return ResourceManager.GetString("ButtonPlanillaDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente:.
        /// </summary>
        public static string LabelCliente {
            get {
                return ResourceManager.GetString("LabelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección:.
        /// </summary>
        public static string LabelDireccion {
            get {
                return ResourceManager.GetString("LabelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Dirección:.
        /// </summary>
        public static string LabelDireccionUrl {
            get {
                return ResourceManager.GetString("LabelDireccionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa:.
        /// </summary>
        public static string LabelEmpresa {
            get {
                return ResourceManager.GetString("LabelEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        public static string LabelEstado {
            get {
                return ResourceManager.GetString("LabelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        public static string LabelTelefono {
            get {
                return ResourceManager.GetString("LabelTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string SectionInformacion {
            get {
                return ResourceManager.GetString("SectionInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polizas.
        /// </summary>
        public static string TextSeccionResultado {
            get {
                return ResourceManager.GetString("TextSeccionResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportadora Haruhiko.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polizas.
        /// </summary>
        public static string TittleListado {
            get {
                return ResourceManager.GetString("TittleListado", resourceCulture);
            }
        }
    }
}
